
mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
authentication: [""]
allow-lan: true
mode: rule
log-level: warning
ipv6: false
external-controller: :9999
external-ui: ui
secret: 


tun:
  enable: true
  stack: system
  auto-route: true
#  auto-redir: true
#  interface-name: eth1
  auto-detect-interface: true
#  dns-hijack:
#    - any:53

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip 
  listen: 0.0.0.0:253
  use-hosts: true
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 8.8.8.8
  nameserver:
    - 8.8.8.8
  fallback:
    - 8.8.8.8
  fallback-filter:
    geoip: true

store-selected: true

proxy-providers:
  HongKong:
    type: http
    path: ./proxy/HongKong.yaml
    interval: 86400
    url: https://api.subcsub.com/sub?target=clash&url="带转义符的订阅链接"&insert=false&exclude=%E8%AF%95%E7%94%A8&include=%E9%A6%99%E6%B8%AF&append_type=true&emoji=true&list=true&tfo=false&scv=false&fdn=true&sort=true&udp=true&new_name=true
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800

  Japan:
    type: http
    path: ./proxy/Japan.yaml
    interval: 86400
    url: https://api.subcsub.com/sub?target=clash&url="带转义符的订阅链接"&insert=false&exclude=%E8%AF%95%E7%94%A8&include=%E6%97%A5%E6%9C%AC&append_type=true&emoji=true&list=true&tfo=false&scv=false&fdn=true&sort=true&udp=true&new_name=true
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800

  Singapore:
    type: http
    path: ./proxy/Singapore.yaml
    interval: 86400
    url: https://api.subcsub.com/sub?target=clash&url="带转义符的订阅链接"&insert=false&exclude=%E8%AF%95%E7%94%A8&include=%E6%96%B0%E5%8A%A0%E5%9D%A1&append_type=true&emoji=true&list=true&tfo=false&scv=false&fdn=true&sort=true&udp=true&new_name=true
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800

  Taiwan:
    type: http
    path: ./proxy/Taiwan.yaml
    interval: 86400
    url: https://api.subcsub.com/sub?target=clash&url="带转义符的订阅链接"&insert=false&exclude=%E8%AF%95%E7%94%A8&include=%E5%8F%B0%E6%B9%BE&append_type=true&emoji=true&list=true&tfo=false&scv=false&fdn=true&sort=true&udp=true&new_name=true
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800

  USA:
    type: http
    path: ./proxy/USA.yaml
    interval: 86400
    url: https://api.subcsub.com/sub?target=clash&url="带转义符的订阅链接"&insert=false&exclude=%E8%AF%95%E7%94%A8&include=%E7%BE%8E%E5%9B%BD&append_type=true&emoji=true&list=true&tfo=false&scv=false&fdn=true&sort=true&udp=true&new_name=true
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800

proxy-groups:
  - name: fastUSA
    type: url-test
    interval: 600
    tolerance: 50
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    use:
      - USA
      
  - name: fastHongKong
    type: url-test
    interval: 600
    tolerance: 50
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    use:
      - HongKong
      
  - name: fastTaiwan
    type: url-test
    interval: 600
    tolerance: 50
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    use:
      - Taiwan

  - name: fastJapan
    type: url-test
    interval: 600
    tolerance: 50
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    use:
      - Japan

  - name: fastSingapore
    type: url-test
    interval: 600
    tolerance: 50
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    use:
      - Singapore

  - name: fastProxy
    type: url-test
    interval: 600
    tolerance: 50
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    use:
      - Singapore
      - Japan
      - Taiwan
      - USA
      - HongKong
      
  - name: defaultProxy
    type: select
    proxies:
      - fastSingapore
      - fastJapan
      - fastTaiwan
      - fastUSA
      - fastHongKong
      - fastProxy
      
  - name: chatgptProxy
    type: select
    proxies:
      - fastSingapore
      - fastJapan
      - fastTaiwan
      - fastUSA

rule-providers:
  chatgpt_domain:
    behavior: domain
    interval: 86400
    path: ./ruleset/chatgpt_domain.yaml
    type: http
    url: "https://ghproxy.com/https://raw.githubusercontent.com/AfxMsgBox/MyRule/main/ChatGPTDomain"
    
rules:
 - RULE-SET,chatgpt_domain,chatgptProxy
 - MATCH, defaultProxy

