mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
authentication: [""]
allow-lan: true
mode: rule
log-level: warning
ipv6: false
external-controller:  :3721
external-ui: ui
#secret:
tcp-concurrent: true
geodata-loader: memconservative

profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: true
  stack: mixed
  mtu: 1500
  auto-route: false
  auto-redir: false
  auto-detect-interface: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: :253
  use-hosts: false
  fake-ip-range: 172.16.0.1/12
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 223.5.5.5
  fallback:
    - 223.5.5.5
proxy-providers:
  HongKong:
    type: http
    path: ./proxy/HongKong.yaml
    interval: 86400
    url: {SUBSCRIBE_URL}&insert=false&exclude=%E8%AF%95%E7%94%A8&include=%E9%A6%99%E6%B8%AF&append_type=true&emoji=true&list=true&tfo=false&scv=false&fdn=true&sort=true&udp=true&new_name=true
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800

  TaiWan:
    type: http
    path: ./proxy/TaiWan.yaml
    interval: 86400
    url: {SUBSCRIBE_URL}&insert=false&exclude=%E8%AF%95%E7%94%A8&include=%E5%8F%B0%E6%B9%BE&append_type=true&emoji=true&list=true&tfo=false&scv=false&fdn=true&sort=true&udp=true&new_name=true
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800

proxy-groups:
  - name: fastHongKong
    type: url-test
    interval: 600
    tolerance: 50
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    use:
      - HongKong

  - name: fastTaiWan
    type: url-test
    interval: 600
    tolerance: 50
    lazy: true
    url: 'http://www.gstatic.com/generate_204'
    use:
      - TaiWan

rule-providers:
  rule_gpt:
    behavior: domain
    interval: 86400
    path: ./ruleset/gpt.yaml
    type: http
    url: "https://raw.githubusercontent.com/AfxMsgBox/MyRule/main/domain/gpt.txt"

rules:
 - RULE-SET,rule_gpt,fastTaiWan
 - MATCH, fastHongKong
