SUBSCRIBE_URL=https://api.subcsub.com/sub?target=clash&url=
WG_localip=10.66.66.103
WG_privatekey=eCtXsJZ27+4PbhDkHnB923tkUn2Gj59wZw5wFA75MnU=
WG_server=162.159.192.1
WG_serverport=2480
WG_serverpubkey=Cr8hWlKvtDt7nrvf+f0brNQQzabAqrjfBvas9pmowjo=
