#!/bin/sh /etc/rc.common

START=99

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
USE_PROCD=1

CLASH_PROG=/etc/proxy/clash/clash
CLASH_DIR=/etc/proxy/clash
META_PROG=/etc/proxy/meta/mihomo
META_DIR=/etc/proxy/meta

if [ -e $META_PROG ]; then
	CLASH_PROG=$META_PROG
	CLASH_DIR=$META_DIR
fi

start_service() {
  procd_open_instance
  procd_set_param respawn
  procd_set_param stderr 0
  procd_set_param stdout 0
  procd_set_param command  $CLASH_PROG -d $CLASH_DIR
  procd_close_instance
}

stop_service() {
	procd_close_instance
}

service_triggers() {
  procd_add_raw_trigger "interface.utun.up" 5000 "ip route del 172.16.0.0/30 && ip route add 172.16.0.0/12 dev utun"
}
