#!/bin/sh /etc/rc.common

AGH_PROG=/usr/bin/AdGuardHome
AGH_DIR=/etc/proxy/agh
AGH_CONFIG=/etc/proxy/agh/agh.yaml
CLASH_PROG=/etc/proxy/clash/clash
CLASH_DIR=/etc/proxy/clash
META_PROG=/etc/proxy/meta/mihomo
META_DIR=/etc/proxy/meta

# starts after network starts
START=21
# stops before networking stops
STOP=89

SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
USE_PROCD=1

if[ -e $META_PROG ]; then
	CLASH_PROG=$META_PROG
	CLASH_DIR=$META_DIR
	logger "use meta"
fi

start_service() {

	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 0
	procd_set_param stdout 0
	procd_set_param command $CLASH_PROG -d $CLASH_DIR
	procd_close_instance

 	procd_open_instance
        procd_set_param respawn
        procd_set_param stderr 0
        procd_set_param stdout 0
        procd_set_param command $AGH_PROG -c $AGH_CONFIG -w $AGH_DIR --no-check-update
        procd_close_instance
	logger "clash & adh done."
}
