#!/bin/sh /etc/rc.common

PROG=/usr/bin/AdGuardHome
WORK_DIR=/etc/proxy/agh

USE_PROCD=1

START=99
STOP=1

start_service() {
  procd_open_instance
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param command "$PROG" -c $WORK_DIR"/agh.yaml" -w "$WORK_DIR" --no-check-update
  procd_close_instance
}

stop_service() {
    killall AdGuardHome
}
