#!/bin/sh /etc/rc.common

START=98

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
USE_PROCD=1

CLASH_PROG=/etc/proxy/clash/clash
CLASH_DIR=/etc/proxy/clash
META_PROG=/etc/proxy/meta/mihomo
META_DIR=/etc/proxy/meta

if [ -e $META_PROG ]; then
	CLASH_PROG=$META_PROG
	CLASH_DIR=$META_DIR
	logger "use meta"
else
	logger "use clash"
fi

start_service() {
  procd_open_instance
  procd_set_param respawn
  procd_set_param stderr 1
  procd_set_param stdout 1
  procd_set_param command  $CLASH_PROG -d $CLASH_DIR
  procd_close_instance
}
